version: '3'

services: 
  nginx:
    image: nginx:latest
    volumes: 
      - ./:/var/www/
      - ./storage:/var/www/storage
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8876:80
    container_name: shop_nginx
    depends_on: 
     - app

  app: 
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db
    container_name: shop_app

  db:
    image: mysql:8.0
    restart: always
    volumes: 
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: shop_db
